name: turf_booking_app
description: A turf booking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#ffffff"  # or your preferred background
  image: assets/logo.jpg
  android: true
  ios: true

  # Optional: Control the size and positioning
  android_gravity: center
  ios_content_mode: scaleAspectFill  # Similar behavior for iOS
  fullscreen: true
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size:  # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/google_logo.jpg
